### ISSUE TITLE
Google no longer supports Open ID 2.0

### ISSUE THREAD

**Issue by dezfowler** [dddeastanglia/DDDEastAnglia#343] opened 2015-06-10 20:58 UTC
Trying to log in to the DDD EA site using my Google account but it uses Open ID 2.0 which Google no longer supports...

 https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by adrianbanks** [comment] 2015-06-10 21:33
Duplicate of #333.

**Closed as completed by adrianbanks** 2015-06-10 21:33 UTC
